FROM python:3.12-slim

# System deps. Кроме git нужны редакторы (rebase -i, commit без -m, mergetool,
# разрешение конфликтов) и привычные интерактивные утилиты терминала.
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
        git bash curl ca-certificates \
        vim nano less \
        man-db procps tree file \
        ncurses-bin bash-completion && \
    rm -rf /var/lib/apt/lists/*

# Python deps
RUN pip install --no-cache-dir fastapi uvicorn[standard] python-multipart

# App source (xterm.js assets bundled in app/static/)
COPY app/ /app/

# Lab data (generated by lab_extractor.py before docker build)
COPY labs/ /labs/

# Git global config for student terminal sessions
RUN git config --global init.defaultBranch main && \
    git config --global user.email "student@git-playground.local" && \
    git config --global user.name "Student" && \
    git config --global core.editor nano
ENV EDITOR=nano VISUAL=nano

WORKDIR /app
EXPOSE 3000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]
